### ISSUE TITLE
Tooltip on Button in ButtonGroup shifts Buttons on Hover

### ISSUE THREAD

**Issue by jtstrohl** [gwtbootstrap3/gwtbootstrap3#239] opened 2014-10-16 13:08 UTC
I have a ButtonGroup with Icon Buttons to be used as a toolbar.  Each Icon Button has a static text Tooltip to explain what the Button is used for.

My UIBinder declaration is very simple, and there is no functional code behind the button yet:
```
<b:ButtonGroup>
    <b:Tooltip text="Add" trigger="HOVER" placement="AUTO">
        <b:Button icon="PLUS" type="PRIMARY" ui:field="btnAdd" />
    </b:Tooltip>
    ...
</b:ButtonGroup>
```

The trigger for all of my Tooltips is HOVER.  When I hover over the buttons with the mouse, the Tooltip is successfully displayed.

However, the issue I have is that as the Tooltip is initially displayed, the Button's size briefly increases in width (only slightly, and only for a second; then readjusts to normal size).  This increase in size temporarily shifts all of the following Buttons in the ButtonGroup to the right, making the ButtonGroup "twitch" or "jiggle" as the Tooltip is displayed.

This is not really a functional issue, but it is very irritating to the user/customer.  I have tried applying several themes to make sure this is not just a CSS styling issue, but the behavior is the same on all.

**Comment by ArloL** [comment] 2015-02-03 21:08
It looks like you forgot to initialize the tooltips. They're "opt-in": http://getbootstrap.com/javascript/#tooltips

I could reproduce the problem with vanilla bootstrap: http://jsbin.com/sexilogure/2/

See http://jsbin.com/sexilogure/2/edit for source.

@jtstrohl Do you want to report that to the bootstrap team?

**Comment by jtstrohl** [comment] 2015-02-04 18:01
Thanks for the response, @ArloL...

So are you saying that the gwtbootstrap3 implementation should be including this initialization?  If so, then I think it should be characterized as a bug to avoid the unwanted side effects (such as the element growing wider and/or losing its rounded corners when the tooltip is triggered) mentioned here: http://getbootstrap.com/javascript/#tooltips

Thanks.

**Comment by ArloL** [comment] 2015-02-04 18:10
What do you mean exactly by "including this initialization"?
I was talking about your bootstrap sample code. As you mentioned you could not reproduce the problem with vanilla bootstrap. But you did not initialize the tooltips correctly. Thus the problem did not present itself. It does in my sample.

Now that you mention it I see the appropriate paragraph about button groups. Using `data-container="body"` works: http://jsbin.com/jibekadafa/2/edit / http://jsbin.com/jibekadafa/2/

You should simply do this

~~~~
<b:ButtonGroup>
    <b:Tooltip text="Add" trigger="HOVER" placement="AUTO" container="body">
        <b:Button icon="PLUS" type="PRIMARY" ui:field="btnAdd" />
    </b:Tooltip>
    ...
</b:ButtonGroup>
~~~~

**Comment by jtstrohl** [comment] 2015-02-04 18:15
So specifying the container as "body" for the tooltip will avoid the "jiggle" effect?

We actually ended up abandoning bootstrap for custom CSS, but hopefully this will help someone else who runs into this problem.

**Comment by ArloL** [comment] 2015-02-04 18:17
> So specifying the container as "body" for the tooltip will avoid the "jiggle" effect?
Yes.

Would you be so kind and close this issue please? Thanks.

**Comment by jgodi** [comment] 2015-02-06 17:55
Thank you @ArloL for explaining and investigating this issue.

**Closed by jgodi** 2015-02-06 17:56 UTC
Labels: bug
